on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - run: nginx -v
            - run: ansible-playbook -i .github/workflows/inventory.ini ,github/workflows/main.yml
